#!/bin/bash

# Give the opportunity the caller of the script to specify the directory
# where the repository is located, otherwise default to the current
# directory
REPOPATH=${1:-$PWD}

# Use pushd here so when the script exits, the CWD will automatically
# be the initial one before calling this script.
pushd $REPOPATH

# kernelci is using abbrev=12 inherited from Jenkins
ABBREV=12

# Get the git description conforming to kernelci
GIT_DESCR=$(git describe --abbrev=$ABBREV)

# Build the url
KERNELCI_URL=https://storage.kernelci.org/pmwg/$GIT_DESCR/build-logs-summary.txt

BLAME_SCRIPT=pmwg-ci-blame

pmwg-ci_report() {

    URL=$KERNELCI_URL

    curl -s -f $URL -o - | while read -r ERROR; do

	# ignore commented lines
	echo $ERROR | egrep -q '(^#|^\s*$|^\s*\t*#)' && continue

	FILE=$(echo $ERROR | awk '{ print $2 }' | awk -F ':' '{print $1}')
	LINE=$(echo $ERROR | awk '{ print $2 }' | awk -F ':' '{print $2}')

	echo "Investigating \"$ERROR\" ..."
	$BLAME_SCRIPT $FILE $LINE "$ERROR"

    done
}

pmwg-ci_report
