#!/bin/bash

GIT_DESCR=$(git describe)
KERNELCI_URL=https://kernelci.org/build/pwmg/kernel/$GIT_DESCR
BLAME_SCRIPT=powerci-blame

powerci_report() {

    URL=$KERNELCI_URL/$1

    echo "Downloading $URL ..."

    curl -f $URL -o - | while read -r ERROR; do

	# ignore commented lines
	echo $ERROR | egrep -q '(^#|^\s*$|^\s*\t*#)' && continue

	FILE=$(echo $ERROR | awk '{ print $2 }' | awk -F ':' '{print $1}')
	LINE=$(echo $ERROR | awk '{ print $2 }' | awk -F ':' '{print $2}')

	echo "Investigating \"$ERROR\" ..."
	$BLAME_SCRIPT $FILE $LINE "$ERROR"

    done
}

powerci_report errors.txt
powerci_report warnings.txt
